### ISSUE TITLE
Display `__note__` from monkeypatched `TracebackException` type

### ISSUE THREAD

**Issue by Zac-HD** [agronholm/exceptiongroup#1]
:wave: [PEP-678](https://www.python.org/dev/peps/pep-0678/) author here - I've been looking at how to port Hypothesis over to use `ExceptionGroup` (https://github.com/HypothesisWorks/hypothesis/pull/3191).  If this backport started displaying the `__note__` string if present, I'd be able and very happy to throw out all* the old print-based code entirely!  I'm happy to implement this, if you'd be willing to take a PR and cut the release?

\*aside from a print-based, single-exception-only fallback for if monkeypatching is disabled on Python <3.11.

**Comment by agronholm** [comment]
But where would `__note__` even come from, on Python < 3.11?

**Comment by Zac-HD** [comment]
From Hypothesis switching from `print("Failing example: ...")` to `err.__note__ = "Failing example: ..."`!

`BaseException` at al don't define slots, so you can assign to it on any version of Python!  It just doesn't get displayed in the traceback unless you're using Python 3.11+ (assuming the PEP is accepted)... or somebody monkeypatches `TracebackException` :wink:   Which I'd rather ship here than in Hypothesis, to avoid potential conflicts.

**Comment by agronholm** [comment]
Ok, I don't suppose there is any harm in doing so. If the PEP ends up being rejected, I reserve the right to remove that code though. Note that there are parts in the test suite where assertions specific to `__note__` have been commented out, and those should be uncommented.

**Comment by Zac-HD** [comment]
Certainly; if the PEP is rejected I'll be ripping the relevant code out of Hypothesis too!
