### ISSUE TITLE
Incorrect `Self` import breaks pyright type-checking

### ISSUE THREAD

**Issue by jakkdl** [agronholm/exceptiongroup#100]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Exceptiongroup version

1.2.0

### Python version

3.10

### What happened?

.

### How can we reproduce the bug?

https://github.com/microsoft/pyright/issues/6795

**Comment by agronholm** [comment]
I'm not super thrilled to add a dependency (even a conditional one) to a project that is currently dependency free, and for something that provides no benefits at run time. Is there any way around this?

**Comment by jakkdl** [comment]
> I'm not super thrilled to add a dependency (even a conditional one) to a project that is currently dependency free, and for something that provides no benefits at run time. Is there any way around this?

Ah, there is! Self is a convenience class that can be replaced by usage of `TypeVar` - see https://docs.python.org/3/library/typing.html#typing.Self
And `TypeVar` is available in the stdlib since 3.5
