### ISSUE TITLE
Minor difference between cpy3.11 BaseExceptionGroup.derive and this project

### ISSUE THREAD

**Issue by cfbolz** [agronholm/exceptiongroup#111]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Exceptiongroup version

main

### Python version

3.10

### What happened?

This is a completely minor difference, but I wanted to mention it anyway. In CPython 3.11, the `__notes__` attribute is *not* copied over by the `BaseExceptionGroup.derive` method. See terminal session below.

However, in the pure Python implementation in this repo it does:

```python
    def derive(
        self, __excs: Sequence[_BaseExceptionT]
    ) -> BaseExceptionGroup[_BaseExceptionT]:
        eg = BaseExceptionGroup(self.message, __excs)
        if hasattr(self, "__notes__"):
            # Create a new list so that add_note() only affects one exceptiongroup
            eg.__notes__ = list(self.__notes__)

        return eg
```

this means that if you subclass `(Base)ExceptionGroup` and override `derive`, you have to remember to copy the `__notes__` field, whereas in CPython 3.11 this isn't necessary. We could open a PR to fix this if you that's helpful.

Thanks a lot for the backport in any case! We are basing the PyPy implementation of exception groups on this code.

### How can we reproduce the bug?

```pycon
**Python 3.11.0rc1 (main, Aug 12 2022, 10:02:14) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.**
>>> eg = ExceptionGroup("abc", [ValueError(), TypeError()])
>>> eg.add_note("def")
>>> eg.__notes__
['def']
>>> eg2 = eg.derive([ValueError()])
>>> eg2.__notes__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'ExceptionGroup' object has no attribute '__notes__'. Did you mean: '__ne__'?
```

**Comment by agronholm** [comment]
> this means that if you subclass (Base)ExceptionGroup and override derive, you have to remember to copy the __notes__ field, whereas in CPython 3.11 this isn't necessary. We could open a PR to fix this if you that's helpful.

I'm confused – if the *expected* behavior is to *not* copy the `__notes__` field, then why would the overridden `derive()` method have to copy it?

**Comment by agronholm** [comment]
At any rate, such a behavior difference with CPython is undesirable, and I would accept a PR to rectify this.

**Comment by cfbolz** [comment]
> At any rate, such a behavior difference with CPython is undesirable, and I would accept a PR to rectify this.

ok, will work on a PR. what's the approach with respect to tests for the behaviour? Should I change test_exceptions.py or is that supposed to be an identical copy from the standard-library?

**Comment by cfbolz** [comment]
closing the issue, the PR got merged.
