### ISSUE TITLE
Type error with pyright when creating BaseExceptionGroup

### ISSUE THREAD

**Issue by jakkdl** [agronholm/exceptiongroup#117]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Exceptiongroup version

master/

### Python version

3.11.8

### What happened?

foo.py:
```python
from exceptiongroup import BaseExceptionGroup
g = BaseExceptionGroup("", (KeyboardInterrupt(),))
```
```
$ pyright --pythonversion=3.10 foo.py
/home/h/Git/exceptiongroup/foo.py
  /home/h/Git/exceptiongroup/foo.py:2:5 - error: 
    Could not bind method "__new__" because "type[BaseExceptionGroup[_BaseExceptionT_co@BaseExceptionGroup]]" is not assignable to parameter "cls"
      Type "type[BaseExceptionGroup[_BaseExceptionT_co@BaseExceptionGroup]]" cannot be assigned to type "BaseExceptionGroup[Unknown]"
        "type[type]" is incompatible with "type[BaseExceptionGroup[Unknown]]" (reportGeneralTypeIssues)
1 error, 0 warnings, 0 informations
```

Using `ExceptionGroup` and e.g. `ValueError` gives no error.

### How can we reproduce the bug?

pyright==1.1.358

**Comment by agronholm** [comment]
Any idea on what the cause is?

**Comment by jakkdl** [comment]
it might just be a silly missing `type[]`, I think I managed to fix it by changing L61 to
```python
        cls: type[_BaseExceptionGroupSelf],
```
