### ISSUE TITLE
Release candidate promotion

### ISSUE THREAD

**Issue by xaviergmail** [agronholm/exceptiongroup#20]
Just a quick question, I'm not sure where else to ask. All of the released versions are currently marked as release candidates. I use Pipenv at work and a package that depends on this. My two options for getting pipenv to resolve `exceptiongroup` are either setting `allow_prereleases = true` (which breaks things like PyYAML) in my Pipfile or explicitly stating `exceptiongroup = "~=1.0.0rc8"`.

Will `1.0.0` will be released in line with Python 3.11?

**Comment by agronholm** [comment]
> Will `1.0.0` will be released in line with Python 3.11?

Yes, that was the plan, to avoid any last minute compatibility changes. I would also like to resolve the currently open issues before that.

It sounds like you have found a workaround for the lack of a final release. The 3.11 release is right around the corner so it shouldn't be too long for exceptiongroup v1.0.0 either.
