### ISSUE TITLE
Final 1.0.0 version?

### ISSUE THREAD

**Issue by kloczek** [agronholm/exceptiongroup#24]
Hi,

Do you have any plans to make final 1.0.0 version? 🤔

**Comment by agronholm** [comment]
Yes, along with CPython 3.11.0 final.

**Comment by kloczek** [comment]
Looks like just releaed new pytest 7.2.0 started using `exceptiongroup`.

**Comment by agronholm** [comment]
See #33 for why I haven't made a final release yet.

**Comment by agronholm** [comment]
I've released v1.0.0 final now.
