### ISSUE TITLE
Bizarre error in `sys.excepthook` with recursive calls

### ISSUE THREAD

**Issue by Zac-HD** [agronholm/exceptiongroup#33]
```python-traceback
Error in sys.excepthook:
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.10.4/lib/python3.10/site-packages/exceptiongroup/_formatting.py", line 71, in exceptiongroup_excepthook
    sys.stderr.write("".join(traceback.format_exception(etype, value, tb)))
  File "/root/.pyenv/versions/3.10.4/lib/python3.10/traceback.py", line 136, in format_exception
    return list(te.format(chain=chain))
  File "/root/.pyenv/versions/3.10.4/lib/python3.10/site-packages/exceptiongroup/_formatting.py", line 206, in format
    yield from exc.exceptions[i].format(chain=chain, _ctx=_ctx)
  File "/root/.pyenv/versions/3.10.4/lib/python3.10/site-packages/exceptiongroup/_formatting.py", line 142, in format
    if exc.__cause__ is not None:
AttributeError: 'PatchedTracebackException' object has no attribute '__cause__'. Did you mean: '__class__'?
```

I'm pretty sure this is because [the upstream `__init__` method doesn't assign `__cause__` for recursive calls](https://github.com/python/cpython/blob/dddbbd9e3e4e12ed5a805dd4e08953e3332a15ea/Lib/traceback.py#L525-L567), and so if you happen to hit this (on `exceptiongroup == 1.0.0rc9`) you subsequently crash with an AttributeError.  

I think the obvious `getattr(exc, "__cause__", None)` patch is probably the best way forward; happy to write that if you'd like.  Unfortunately I don't have a good reproducing case or indeed any way to reproduce this locally - it's consistently crashing _only_ in a particular build and CI system, and at time of writing I've worked out why but not constructed a repro.

**Comment by agronholm** [comment]
The behavior seems to have changed in Python 3.10. But even that seems to unconditionally assign both `__cause__` and `__context__` to every TE. So a reproducing snippet would be really welcome. I'm not comfortable patching the code until I understand what's going on.

**Comment by agronholm** [comment]
Python 3.11 was just released. I've said that I wanted to release the v1.0.0 final of this backport when that happens, but with a problem like this lurking in the code, I don't want to do that yet. I would appreciate at least some hints. You said you had worked out why it happens, so please share with the class?

**Comment by Zac-HD** [comment]
Based on reading the implementation I thought that this could happen if (something weird happened and) we created a `__cause__`-free TE, but I haven't yet managed to get a reproducer smaller than "an end-to-end stresstest".  Getting something debuggable and then sharable is my top priority for up to the next few days though - sorry to report this so close to the release date!

**Comment by agronholm** [comment]
Thanks, that should help me get started on the fix.

**Comment by agronholm** [comment]
Yeah, I can confirm that the above code fails *only* on Python 3.10. Works fine on 3.9 and 3.11.

**Comment by agronholm** [comment]
I've now turned this into a test that only fails on py3.10.

**Comment by agronholm** [comment]
I'm currently pursuing a few possible avenues for fixing this. Straight up copying code from the stdlib would be dubious considering the amount of private API calls it makes, and the fact that this has to work on older Pythons as well.

**Comment by agronholm** [comment]
Uhm...my first attempt ended up with Python 3.10 working and the rest failing. Back to the drawing board :sweat_smile:

**Comment by agronholm** [comment]
Ok, I finally got it working across the board. Please review the PR so we can get the final release out. Thanks!

**Comment by agronholm** [comment]
Ok, v1.0.0 final is out now!
