### ISSUE TITLE
`with exceptiongroup.catch({Exception: async_fn}):` is a tempting and silent footgun

### ISSUE THREAD

**Issue by Zac-HD** [agronholm/exceptiongroup#66]
It's surprisingly easy to write a handler which silently discards exceptions that you thought were handled:

```python
import asyncio
from exceptiongroup import ExceptionGroup, catch

async def handler(eg):
    # Log some stuff, then re-raise
    raise eg

async def main():
    with catch({TypeError: handler}):
        raise ExceptionGroup("message", TypeError("uh-oh"))

asyncio.run(main())
```
and in a large program, all too easy to miss your only warning:
```python-traceback
$ python t.py 
exceptiongroup/_catch.py:52: RuntimeWarning: coroutine 'handler' was never awaited
  handler(matched)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

...the problem being that we expect _sync_ handlers, and [so we just call it](https://github.com/agronholm/exceptiongroup/blob/9bfc03f402cca2d671a42d00dafb56f5c1e75847/src/exceptiongroup/_catch.py#L52) - which if it's an async function won't actually run the body of the handler, and thus won't re-raise any exception, which is treated as success.

--------------------

IMO this code is unrecoverably correct, and we should bail out with an error as soon as possible.  Based on [Trio's internal comments](https://github.com/python-trio/trio/blob/314663806cbaf717d70d70b71631e340396a1bb1/trio/_util.py#L137-L140) we should rely on checking the return value rather than inspecting the handler callable - I suspect doing an initial branch on `is not None` would keep things super-fast for the vast majority of happy cases.  Thoughts?

**Comment by agronholm** [comment]
We could use `inspect.iscoroutinefunction()` and raise `TypeError` or something on a positive. It's an extra step for everyone who's using this correctly, but maybe the performance hit isn't noticeable.

**Comment by agronholm** [comment]
Ok, so the consensus is to use `inspect.iscoroutine()` on the return value?

**Comment by Zac-HD** [comment]
Sounds good to me!
