### ISSUE TITLE
Backport changes to `contextlib.suppress()`?

### ISSUE THREAD

**Issue by Zac-HD** [agronholm/exceptiongroup#91]
https://github.com/python/cpython/pull/103792 modified `contextlib.suppress()` to support `ExceptionGroup`s, by removing suppressed exceptions.  If there are no remaining exceptions in the group it's caught; otherwise the remainder is re-raised.

It seems useful to provide this behavior to `exceptiongroup` users on Python < 3.12 (notably including 3.11, where `ExceptionGroup` is built in but `suppress()` did not handle it).

**Comment by agronholm** [comment]
I wonder if `BaseExceptionGroup` was intentionally not supported there.

**Comment by Zac-HD** [comment]
Irit thinks it was an accident, so I'll have a PR up against CPython shortly.

**Comment by agronholm** [comment]
Yep, I figured as much :)

**Comment by Zac-HD** [comment]
PR merged, will ship in Python 3.12.1 🙂
