### ISSUE TITLE
Example code in README.md raises errors in mypy

### ISSUE THREAD

**Issue by jakkdl** [agronholm/exceptiongroup#97]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Exceptiongroup version

1.2.0

### Python version

3.11.5

### What happened?

```
$ cat foo.py
from exceptiongroup import ExceptionGroup, catch

def value_key_err_handler(excgroup: ExceptionGroup) -> None:
    for exc in excgroup.exceptions:
        print('Caught exception:', type(exc))

def runtime_err_handler(exc: ExceptionGroup) -> None:
    print('Caught runtime error')

with catch({
    (ValueError, KeyError): value_key_err_handler,
    RuntimeError: runtime_err_handler
}):
    ...


$ mypy foo.py
foo.py:11: error: Dict entry 0 has incompatible type "tuple[type[ValueError], type[KeyError]]": "Callable[[ExceptionGroup[Any]], None]"; expected "type[BaseException] | Iterable[type[BaseException]]": "Callable[[BaseException], Any]"  [dict-item]
foo.py:12: error: Dict entry 1 has incompatible type "type[RuntimeError]": "Callable[[ExceptionGroup[Any]], None]"; expected "type[BaseException] | Iterable[type[BaseException]]": "Callable[[BaseException], Any]"  [dict-item]
Found 2 errors in 1 file (checked 1 source file)
```

I expected no errors

### How can we reproduce the bug?

mypy version 1.7.0, no configuration.

**Comment by agronholm** [comment]
The best I can do is make it so that the handler is typed to receive `BaseExceptionGroup` instead of `BaseException`. But I don't know any way to convey to mypy when the handler should accept `ExceptionGroup` instead.

**Comment by jakkdl** [comment]
> The best I can do is make it so that the handler is typed to receive `BaseExceptionGroup` instead of `BaseException`. But I don't know any way to convey to mypy when the handler should accept `ExceptionGroup` instead.

when "should" it only accept `ExceptionGroup` and not `BaseExceptionGroup`?

(also randomly spotted that the third code block in the readme is not formatted as python code)

**Comment by agronholm** [comment]
> when "should" it only accept `ExceptionGroup` and not `BaseExceptionGroup`?

When all of the exception classes assigned to the handler derive from `Exception`.

**Comment by jakkdl** [comment]
> > when "should" it only accept `ExceptionGroup` and not `BaseExceptionGroup`?
> 
> When all of the exception classes assigned to the handler derive from `Exception`.

hmm. Yeah not possible with `Mapping`/`dict` as far as I can tell. Though possible if `catch` instead took an `*args` with tuples:
```python
from typing import Callable, Iterable

def catch(
    *handlers: tuple[
        type[Exception] | Iterable[type[Exception]], Callable[[ExceptionGroup], object]
    ]
    | tuple[
        type[BaseException] | Iterable[type[BaseException]],
        Callable[[BaseExceptionGroup], object],
    ]
): ...

def handler(e: ExceptionGroup) -> None: ...
def handler_base(e: BaseExceptionGroup) -> None: ...

catch((ValueError, handler), (KeyboardInterrupt, handler_base))
catch((KeyboardInterrupt, handler))  # type: ignore[arg-type]
```

Maybe worth adding support for that way of calling it as well and do a light deprecation of passing a dict.

**Comment by agronholm** [comment]
Oh, it just wanted me to fill in the type parameter for `BaseExceptionGroup`.

**Comment by bastimeyer** [comment]
I just ran into this issue with mypy, but then found the fix on the master branch and this bug report. Is there a chance for a 1.2.1 release with this fix included, so that the code pulled from PyPI doesn't raise typing errors? Thanks!
